total: 2.e2
num_pixs: 64
n_coeffs_low: 0
n_coeffs_high: 6
noise: 0.02
stateNoise: 0.00
alpha: 0.00
alpha2: 0.00
isWaveplate: False
max_waveplate: 2
maxAng: 5
apply_inversion: False
sixMeasure: False

filename: '64by64_200_fullDataset_fiveMeas'














