init_lr: '1.e-3'
min_lr: '1.e-7'
epochs_to_update: 15
lr_factor: 0.1
num_of_epochs: 200
model_path: 'models/64Net_test'
model_name: '64Net_test'
load_model: False
old_model_name: 64Net_wps_10percent
nnType: 2
num_pixs: 64
batchSize: 8
kernelSize: 3
dropRate: 0.2
layers: 1
sigma: 0.00
enableGPU: True
enableDataGen: False
shuffle: True
sixMeasure: False
valSplit: 0.85

datafile: 64by64_200_fullDataset_fiveMeas.pkl

freezeLayers: False
freeze_policy_begin: 0
freeze_policy_end: 19


train_params: {'batch_size': 32,
                'batches_per_epoch': 1064,
                'noise' : 0.02,
                'stateNoise': 0.00, 
                'alpha': 0.00, 
                'res': 32,
                'n_coeff_high': 6, 
                'n_coeff_low': 0,
                'isWaveplates': False,
                'maxAng': 5
                  }

val_params: {'batch_size': 32,
              'batches_per_epoch': 188,
              'noise' : 0.02,
              'stateNoise': 0.00,
              'alpha': 0.00,
              'res': 32,
              'n_coeff_high': 6, 
              'n_coeff_low': 0,                
              'isWaveplates': False,
              'maxAng': 5
                }









